### ISSUE TITLE
convertBuffer() is wrong for S24 and ALSA

### ISSUE THREAD

**Issue by knell** [thestk/rtaudio#74] opened 2016-08-22 10:44 UTC
For 24 bit sample format ALSA uses full 32 bit word and takes only 24 bits of data. In the convertBuffer() you use S24 pointer to iterate buffer and it's wrong for ALSA. For example, lines 9827-9838, there is:
Int24 *in = (Int24 *)inBuffer;
for ALSA you will take only three bytes from input buffer but you should take 4, like this:
Int32 *in = (Int32 *)inBuffer;
and later convert a value to Int24 to extract an integer.
The same in the line 9943, there is:
Int24 *out = (Int24 *)outBuffer;
so you will write 3 bytes of output but for ALSA it should be four. Now it writes only 3/4 of the buffer and the last 1/4 remains untouched. Actually it would be good to memset a buffer with 0 after calloc().

Also, there is no support of big endian formats (in S24 for example) but it should be like 'feature request', not a bug.

**Comment by garyscavone** [comment] 2016-08-22 15:53
The convertBuffer() function is general to the various data types and should not be modified to address a problem with a specific API. The Int24 data type is a class (defined in RtAudio.h) that support 24-bit data and provides functions to convert to other different types.

But if there is a problem with the support for ALSA 24-bit data, it should be fixed in the ALSA API section of the RtAudio code.  That could potentially involve not using the Int24 data type at all and instead just calling the convertBuffer() function for 32-bit data.  I won’t have time to look into this for a while.

**Comment by garyscavone** [comment] 2017-08-22 23:18
No follow-up ... assuming it was not a bug.

**Closed by garyscavone** 2017-08-22 23:18 UTC
