### ISSUE TITLE
Specify arbitrary number of I/O channels when using Jack

### ISSUE THREAD

**Issue by hires** [thestk/rtaudio#123] opened 2018-01-04 01:07 UTC
Thanks for RtAudio, I use it all the time!

I upgraded to version 5.0.0 so I could use the feature to not connect Jack ports automatically. But I realized I also need to be able to have my app present a large number of audio I/O ports, probably more/different than the actual audio hardware on the system.

It seems that RtAudio can only open an actual "device" instead of just presenting itself as a collection of channels. I'd like to, for instance, specify a device ID of -1 or something and have my app show up with as many I/O ports as I'd like, instead of trying to bind with a specific device already on the system.

Is this possible or practical? Thanks!

**Comment by radarsat1** [comment] 2018-01-14 18:07
Hi, I think we're open to suggestions but it's not clear how it should be done.  Ideas?

**Comment by hires** [comment] 2018-01-14 18:59
Currently if the number of channels to open has to be <= the number of channels on the device in Jack. On my system (Linux Mint 18) the "system" device (which is my sound card) always appears as device 0. Other jack clients are listed after.

When I start my program with RtAudio, the program name appears in Jack, and is automatically wired to the device I choose. If the device is stereo, and I specify 1 channel, only that channel is wired up. But if I want to work on code that handles 8 channels, I can't choose the stereo device, even if I plan to hook up only two of the channels, or multiply connect channels like 1,3,5,7 to channel 1, and 2,4,6,8 to channel 2, or something like that.

So to make it more flexible there are basically two features needed:

- Start up and connect to Jack with a device named by the program. (which already happens) But don't request to actually connect to any particular device. Perhaps requesting a deviceId of -1 would be a decent notation for this. It's almost exactly what the RTAUDIO_JACK_DONT_CONNECT option does, except the channels wouldn't need to match the channel count of an existing device on the system.

- The other thing that would be needed is a way to connect / disconnect devices within Jack. I assume there is already a Jack API for all these things, but if there were RtAudio hooks to do this it would be great. Then a program could start up and make its connections automatically without relying on an external Jack control program. I found myself doing this manually a few times for development using qjackctl, but every time I killed my app my connections would be lost. My current workaround is to route test signals on my hardware mixing console's busses. Seems overkill and too big to take to the cafe when I want to get out of the studio. :)

Hope this helps to explain the idea. Let me know if there's anything else I can do.

**Comment by dromer** [comment] 2018-07-10 23:52
@hires use a session manager for ladish to maintain your connections (I use claudia)

**Comment by dromer** [comment] 2018-07-11 11:37
It should indeed be possible for rtaudio to present its own virtual audio device to jack based on whatever number of in/out's you require.

There should not be a limitation on which other jack-source you select. (ie. ardour/qtractor with a number of tracks)
Currently it seems that when using jack you have to select 'some' virtual audio device (can be physical or virtual like another program) and base the number of channels on that, which doesn't make a lot of sense.
(see my examples in the VCVRack/Rack thread)

**Comment by jpcima** [comment] 2018-08-09 14:35
I can reproduce this issue and I can surely make a fix for this. I was the original author for the patch of `JACK_AUDIO_DONT_CONNECT`.

Below is a test case for arbitrary channel counts.
[test.cc](https://gist.github.com/jpcima/044c1040236fed413d5adf91deaa90fe)

I was to notice a related and more curious error inside RtAudio:
my sound card is 10 port, but would let me open up to 11 channels! and raise error only at 12 and up.
Upon a closer look, it's noticeable that `jack_get_ports` as used in RtAudio counts the midi port as audio channel.

After a change of code, the channels were correctly counted.
Before `ports = jack_get_ports( client, deviceName.c_str(), NULL, flag );`
After `ports = jack_get_ports( client, deviceName.c_str(), JACK_DEFAULT_AUDIO_TYPE, flag );`

I'll submit a PR for a fix of this shortly.

**Comment by dromer** [comment] 2018-08-09 15:20
Ah fantastic. This looks like a way forward to get proper jack-client capabilities.

**Comment by radarsat1** [comment] 2019-02-25 11:00
Closing because fix merged.

**Closed by radarsat1** 2019-02-25 11:00 UTC
