### ISSUE TITLE
Access Violation with ASIO duplex example

### ISSUE THREAD

**Issue by Boscop** [thestk/rtaudio#89] opened 2017-06-06 03:51 UTC
When I run `duplex 2 44100 5 5` on Win 8.1 it works the first time, but when I press Enter (or Ctrl-C) to terminate it, it crashes with an access violation during asioCloseDriver:
![](https://i.imgur.com/ihVKOR8.png)

When I then cancel and rerun it, it doesn't work but crashes already on start with this:
![](https://i.imgur.com/kd3aODD.png)

It seems the device is left in a corrupted state from the previous crash. Because no matter how often I try to rerun the duplex example, it always crashes on start (after the first crash described above) BUT when I run audioprobe.exe it seems to reset the device because after that it works again (but only until I try to terminate it the first time, then it's back to the same situation).

My device 5 is Steinberg UR22:
```
Device Name = Yamaha Steinberg USB ASIO
Probe Status = Successful
Output Channels = 2
Input Channels = 2
Duplex Channels = 2
This is NOT the default output device.
This is NOT the default input device.
Natively supported data formats:
  32-bit int
Supported sample rates = 44100 48000 88200 96000 176400 192000
```

**Comment by garyscavone** [comment] 2017-08-15 22:04
Can anyone check this? I don't want to get anywhere near Win 8.1.

**Comment by tay10r** [comment] 2017-09-12 21:22
I could not reproduce this on my Windows 8.1 machine. But my best guess is that the stream gets aborted and closed by two threads at the same time. It's hard to reproduce, but at least one of those access violations can be fixed by a simple null pointer check.

**Comment by garyscavone** [comment] 2022-07-01 22:22
Closing due to age and lack of further responses for others.

**Closed by garyscavone** 2022-07-01 22:22 UTC
