### ISSUE TITLE
ALSA: Missing "default" device

### ISSUE THREAD

**Issue by gillesdegottex** [thestk/rtaudio#270] opened 2020-09-09 17:13 UTC
The default device on ALSA is sometimes missing, or being busy, unaccessible from ALSA.
Eg. there is currently a known issue reported as `ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection terminated`

So the device id `0` is not always the default ALSA device.

In such situation, line here:
https://github.com/thestk/rtaudio/blob/d7f12763c55795ef8a71a9b589b39e7be01db7b2/RtAudio.cpp#L7562
just shifts all ALSA device ids, so that the wrong device id N+1 is picked up when opening the device id N.

In the same way, the sections

>   result = snd_ctl_open( &chandle, "default", SND_CTL_NONBLOCK );
  if ( result == 0 ) {
    if ( nDevices++ == device ) {
      strcpy( name, "default" );
      goto foundDevice;
    }
  }

in `getDeviceInfo` and `getDeviceCount` will always be sloppy as long as this "default" device appears or not.

As a potential solution, I suggest to not make special cases for the "default" device, just drop those sections and thus treat the "default" device as any other one, in order to be independent of its presence.

In order to implement RTAUDIO_ALSA_USE_DEFAULT in `probeDeviceOpen`, we could first search for the id of the device named "default" and then run the rest of `probeDeviceOpen` as for any other device (and fail if this id can't be found).

I'm happy to make PR if the analysis above looks correct to you and you like the solution.

Cheers,

**Comment by radarsat1** [comment] 2020-09-10 13:42
Related #224

**Comment by gillesdegottex** [comment] 2020-09-10 14:01
oh my, sry to have missed that!

**Comment by antonrunov** [comment] 2020-11-24 17:36
I hit very similar issue with
```ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection terminated```
error. But at least in my case the root cause seems to be quite different. In the same place of `RtApiAlsa :: getDeviceInfo` code quoted above, if `snd_ctl_open( &chandle, "default", SND_CTL_NONBLOCK )` is successfull and `device` is not zero, the `chandle` handle will never be closed. This results in that `unable to connect` error after a few open-close cycles. I also have to mention that this error happens even when you actually open the default (0) device. This is because Alsa api calls `getDeviceInfo` for all available devices in the `saveDeviceInfo` function.

The solution is simple - just add missing `snd_ctl_close`:
```
  result = snd_ctl_open( &chandle, "default", SND_CTL_NONBLOCK );
  if ( result == 0 ) {
    if ( nDevices++ == device ) {
      strcpy( name, "default" );
      goto foundDevice;
    }
  }
  if ( chandle )
    snd_ctl_close( chandle );
```
It solved my issue completely.

**Comment by lp35** [comment] 2020-12-01 12:01
Hello,

Thank you very much for the fix, @antonrunov. I had the same issue on my Fedora 33. Can you make a PR for this? So it will be added to the next release! thanks.

**Comment by garyscavone** [comment] 2022-07-01 17:24
I think this has been fixed in the recent device selection code.

**Closed by garyscavone** 2022-07-01 17:24 UTC
