### ISSUE TITLE
apiInfo dereferenced before non-NULL check in RtApiAlsa::closeStream()

### ISSUE THREAD

**Issue by quicky2000** [thestk/rtaudio#245] opened 2020-05-05 08:07 UTC
Hi,

In  **RtApiAlsa::closeStream()**, **apiInfo** is dereferenced at lines:
**RtAudio.cpp:8058**
`apiInfo->runnable = true;`
**RtAudio.cpp:8067**
`snd_pcm_drop( apiInfo->handles[0] );`
**RtAudio.cpp:8069**
`snd_pcm_drop( apiInfo->handles[1] );`

before first non NULL check occuring at line **RtAudio.cpp:8072**
`if ( apiInfo ) {`

**Comment by radarsat1** [comment] 2021-09-15 16:13
The first is guarded by `if ( stream_.state == STREAM_STOPPED )` and the other two are guarded by `if ( stream_.state == STREAM_RUNNING )`.  Since apiInfo set in `probeDeviceOpen`, and the default state is `STREAM_CLOSED`, it doesn't seem to me that `apiInfo` can be null when the stream state is either of those values.  Was this actually an error that was hit, or just the result of a static analysis tool?  I am guessing the latter, so closing, but please re-open if this is a real issue, or include instructions to reproduce the report from a static analysis tool.

**Closed by radarsat1** 2021-09-15 16:13 UTC

**Comment by quicky2000** [comment] 2021-09-16 07:10
You are right it was a report form static analysis tool ( PVS studio ), I forgot to precise.
Thanks for the analysis !

**Comment by radarsat1** [comment] 2021-09-16 08:25
No problem.  It's generally something I'm happy to fix, but I hesitate if an actual problem can't be reproduced, because I don't want to risk introducing problems where there were none.  Putting an `If()` around those statements would not hurt anything but it also does not seem necessary.  This kind of state-based guard is exactly the kind of thing that static analysis tools have trouble with, which is why, although they are valuable tools, their output should be taken with a grain of salt.
